rf2o_laser_odometry:
  ros__parameters:
    laser_scan_topic: /scan
    odom_topic: /odom
    publish_tf: true
    base_frame_id: base_footprint
    odom_frame_id: odom
    init_pose_from_topic: '/myRobot/odometry'
    freq: 10.0
